name: conflict-resolution
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy
  - scipy
  - matplotlib
  - zarr
  - jupyter
  - pip
  - pandas
  - scikit-learn
  - imbalanced-learn 